--INSTITUCION
CREATE TABLE INSTITUCION
(ID_INSTITUCION NUMBER(5) NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
CONSTRAINT INSTITUCION_PK PRIMARY KEY (ID_INSTITUCION)
);
--COLEGIO
CREATE TABLE COLEGIO
(ID_COLEGIO NUMBER (5) NOT NULL,
COLEGIO VARCHAR2 (50) NOT NULL,
CONSTRAINT COLEGIO_PK PRIMARY KEY (ID_COLEGIO)
);
--ANEXO A
CREATE TABLE ANEXO_A 
(NRO_FOLIO_A NUMBER(10) NOT NULL,
FECHA_RECEPCION DATE NOT NULL,
NOMBRE_RECEPTOR VARCHAR2(50) NOT NULL,
CONSTRAINT ANEXO_A_PK PRIMARY KEY (NRO_FOLIO_A)
);
--CONTACTO
CREATE TABLE CONTACTO
(NRO_FOLIO_A NUMBER(10) NOT NULL,
FONO_TRABAJO NUMBER(20),
FONO_DOMICILIO NUMBER (20),
FONO_MOVIL NUMBER (20) NOT NULL,
CODIGO_POSTAL NUMBER (20),
EMAIL VARCHAR2(150) NOT NULL,
CONSTRAINT CONTACTO_PK PRIMARY KEY (NRO_FOLIO_A),
CONSTRAINT CONTACTO_ANEXO_FK FOREIGN KEY (NRO_FOLIO_A) REFERENCES ANEXO_A (NRO_FOLIO_A)
);
--ACREDITACIONES
CREATE TABLE ACREDITACIONES
(NRO_FOLIO_A NUMBER(10) NOT NULL,
CARGA_FAMILIAR NUMBER(1) NOT NULL,
ACREDITA_CARGA_FAMILIAR NUMBER(1),
FECHA_DOC_CARGA_FAMILIAR DATE,
PERTENECE_PUEBLO_IND_ORIG NUMBER(1) NOT NULL,
ACREDITA_PUEBLO_IND_ORIG NUMBER(1),
FECHA_DOC_PUEBLO_IND_ORIG DATE,
TITULO_POSEE NUMBER(1) NOT NULL,
ACREDITA_TITULO NUMBER(1),
FECHA_DOC_TITULO DATE,
CONSTRAINT ACREDITACIONES_PK PRIMARY KEY (NRO_FOLIO_A),
CONSTRAINT ACREDITACION_ANEXO_FK FOREIGN KEY (NRO_FOLIO_A) REFERENCES ANEXO_A (NRO_FOLIO_A)
);
--TIPO TUTULO
CREATE TABLE TIPO_TITULO
(
ID_TIPO_TITULO NUMERIC(2) PRIMARY KEY,
NOMBRE VARCHAR2(25) NOT NULL,
PUNTAJE NUMERIC(4) NULL
);
--TITULO
CREATE TABLE TITULO
(NRO_FOLIO_A NUMBER (10) NOT NULL,
TITULO VARCHAR2 (50),
ID_INSTITUCION NUMBER (5) NOT NULL,
ID_TIPO_TITULO NUMBER (2) NOT NULL,
CONSTRAINT TITULO_PK PRIMARY KEY (NRO_FOLIO_A),
CONSTRAINT TITULO_ACREDITACION_FK FOREIGN KEY (NRO_FOLIO_A) REFERENCES ACREDITACIONES (NRO_FOLIO_A),
CONSTRAINT TITULO_INSTITUCION_FK FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION (ID_INSTITUCION),
CONSTRAINT TITULO_TIPO_TITULO_FK FOREIGN KEY (ID_TIPO_TITULO) REFERENCES TIPO_TITULO (ID_TIPO_TITULO)
);
--ESCOLARIDAD
CREATE TABLE ESCOLARIDAD
(NRO_FOLIO_A NUMBER (10) NOT NULL,
ULTIMO_AÑO VARCHAR2 (25) NOT NULL,
ID_COLEGIO NUMBER(5) NOT NULL,
CONSTRAINT ESCOLARIDAD_PK PRIMARY KEY (NRO_FOLIO_A),
CONSTRAINT ESCOLARIDAD_ACREDITACION_FK FOREIGN KEY (NRO_FOLIO_A) REFERENCES ACREDITACIONES (NRO_FOLIO_A),
CONSTRAINT ESCOLARIDAD_COLEGIO_FK FOREIGN KEY (ID_COLEGIO) REFERENCES COLEGIO (ID_COLEGIO)
);
--DATO DOCUMENTO
CREATE TABLE DATO_DOCUMENTO
(NRO_DATO_DOC NUMBER (10) NOT NULL,
FIRMA_HUELLA_TIMBRE BLOB DEFAULT EMPTY_BLOB() NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT DATO_DOCUMENTO_PK PRIMARY KEY (NRO_DATO_DOC)
);
--ANEXO B
CREATE TABLE ANEXO_B
(NRO_FOLIO_A NUMBER (10) NOT NULL,
NRO_DATO_DOC NUMBER (10) NOT NULL,
CONSTRAINT ANEXO_B_PK PRIMARY KEY (NRO_FOLIO_A),
CONSTRAINT ACREDITACION_ANEXO_B_FK FOREIGN KEY (NRO_FOLIO_A) REFERENCES ACREDITACIONES (NRO_FOLIO_A),
CONSTRAINT DATO_DOC_ANEXO_B_FK FOREIGN KEY (NRO_DATO_DOC) REFERENCES DATO_DOCUMENTO (NRO_DATO_DOC)
);
--CARGA FAMILIAR
CREATE TABLE CARGA_FAMILIAR
(NRO_FOLIO_A NUMBER (10) NOT NULL,
RUN_CARGA NUMBER (10) NOT NULL,
PRIMER_APELLIDO VARCHAR2 (25) NOT NULL,
SEGUNDO_APELLIDO VARCHAR2 (25) NOT NULL,
NOMBRES VARCHAR2 (50) NOT NULL,
RELACION_POSTULANTE VARCHAR2 (60) NOT NULL,
CONSTRAINT CARGA_FAMILIAR_PK PRIMARY KEY (NRO_FOLIO_A, RUN_CARGA),
CONSTRAINT CARGA_ANEXO_B_FK FOREIGN KEY (NRO_FOLIO_A) REFERENCES ANEXO_B (NRO_FOLIO_A)
);
--ENTIDAD_FINANCIERA
CREATE TABLE ENTIDAD_FINANCIERA
(ID_ENTIDAD_FINANCIERA NUMBER (5) NOT NULL,
ENTIDAD_FINANCIERA VARCHAR2 (25),
CONSTRAINT ENTIDAD_FINANCIERA_PK PRIMARY KEY (ID_ENTIDAD_FINANCIERA)
);
--RELACION TITULAR CUENTA
CREATE TABLE RELACION_TITULAR_CUENTA
(ID_RELACION_TITULAR_CUENTA NUMBER (2) NOT NULL,
RELACION_TITULAR_CUENTA VARCHAR2 (25)NOT NULL,
CONSTRAINT RELACION_TITULAR_CUENTA_PK PRIMARY KEY (ID_RELACION_TITULAR_CUENTA)
);
--TIPO CUENTA
CREATE TABLE TIPO_CUENTA
(ID_TIPO_CUENTA NUMBER (2) NOT NULL,
TIPO_CUENTA VARCHAR2 (25) NOT NULL,
CONSTRAINT TIPO_CUENTA_PK PRIMARY KEY (ID_TIPO_CUENTA)
);
--AHORRO
CREATE TABLE AHORRO
(NRO_FOLIO_A NUMBER(10) NOT NULL,
NRO_CUENTA NUMBER (10) NOT NULL,
RUN_TITULAR NUMBER (10) NOT NULL,
FECHA_APERTURA DATE NOT NULL,
MONTO_AHORRADO NUMBER (9) NOT NULL,
ID_ENTIDAD_FINANCIERA NUMBER (5) NOT NULL,
ID_RELACION_TITULAR_CUENTA NUMBER (2) NOT NULL,
ID_TIPO_CUENTA NUMBER (2) NOT NULL,
CONSTRAINT AHORRO_PK PRIMARY KEY (NRO_FOLIO_A),
CONSTRAINT AHORRO_ANEXO_A_FK FOREIGN KEY (NRO_FOLIO_A) REFERENCES ANEXO_A (NRO_FOLIO_A),
CONSTRAINT ENTIDAD_FINANCIERA_AHORRO_FK FOREIGN KEY (ID_ENTIDAD_FINANCIERA) REFERENCES ENTIDAD_FINANCIERA (ID_ENTIDAD_FINANCIERA),
CONSTRAINT RELACION_TITULAR_AHORRO_FK FOREIGN KEY (ID_RELACION_TITULAR_CUENTA) REFERENCES RELACION_TITULAR_CUENTA (ID_RELACION_TITULAR_CUENTA),
CONSTRAINT TIPO_CUENTA_AHORRO_FK FOREIGN KEY (ID_TIPO_CUENTA)REFERENCES TIPO_CUENTA (ID_TIPO_CUENTA)
);

--AHORRO_DATO_DOC
CREATE TABLE AHORRO_DATO_DOC
(
NRO_FOLIO_A NUMBER(10) NOT NULL,
NRO_DATO_DOC NUMBER(10) NOT NULL,
CONSTRAINT pk_ahorro_dato_doc PRIMARY KEY (NRO_FOLIO_A, NRO_DATO_DOC),
CONSTRAINT fk_ahorrodatodoc_ahorro FOREIGN KEY (NRO_FOLIO_A) REFERENCES AHORRO(NRO_FOLIO_A),
CONSTRAINT fk_ahorrodatodoc_datodoc FOREIGN KEY (NRO_DATO_DOC) REFERENCES DATO_DOCUMENTO(NRO_DATO_DOC)
);

--NACIONALIDAD
CREATE TABLE NACIONALIDAD
(ID_NACIONALIDAD NUMBER (3) NOT NULL,
NACIONALIDAD VARCHAR2 (25) NOT NULL,
CONSTRAINT NACIONALIDAD_PK PRIMARY KEY (ID_NACIONALIDAD)
);
--CONVIVIENTE CIVIL
CREATE TABLE CONVIVIENTE_CIVIL
(NRO_FOLIO_A NUMBER(10) NOT NULL,
RUN_CONVIVIENTE NUMBER (10) NOT NULL,
PRIMER_APELLIDO VARCHAR2 (25) NOT NULL,
SEGUNDO_APELLIDO VARCHAR2 (25) NOT NULL,
NOMBRES VARCHAR2 (50) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
ID_NACIONALIDAD NUMBER (3) NOT NULL,
CONSTRAINT CONVIVIENTE_CIVIL_PK PRIMARY KEY (NRO_FOLIO_A),
CONSTRAINT CONVIVIENTE_ANEXO_A_FK FOREIGN KEY (NRO_FOLIO_A) REFERENCES ANEXO_A (NRO_FOLIO_A),
CONSTRAINT CONVIVIENTE_NACIONALIDAD_FK FOREIGN KEY (ID_NACIONALIDAD) REFERENCES NACIONALIDAD (ID_NACIONALIDAD)
);
--ESTADO CIVIL
CREATE TABLE ESTADO_CIVIL
(ID_ESTADO_CIVIL NUMBER (2) NOT NULL,
ESTADO_CIVIL VARCHAR2 (25) NOT NULL,
PUNTAJE NUMBER(4) NULL,
CONSTRAINT ESTADO_CIVIL_PK PRIMARY KEY (ID_ESTADO_CIVIL)
);
--POSTULANTE
CREATE TABLE POSTULANTE
(NRO_FOLIO_A NUMBER (10) NOT NULL,
RUN_POSTULANTE NUMBER (10) NOT NULL,
PRIMER_APELLIDO VARCHAR2 (25) NOT NULL,
SEGUNDO_APELLIDO VARCHAR2 (25) NOT NULL,
NOMBRES VARCHAR2 (50) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
CERTIFICADO_PERMANENCIA NUMBER(1),
FECHA_CERTIFICADO_PERM DATE,
TRAMITE_DIVORCIO NUMBER(1),
FOTOGRAFIA BLOB DEFAULT EMPTY_BLOB() NOT NULL,
ID_NACIONALIDAD NUMBER(3) NOT NULL,
ID_ESTADO_CIVIL NUMBER (2) NOT NULL,
CONSTRAINT POSTULANTE_PK PRIMARY KEY (NRO_FOLIO_A),
CONSTRAINT POSTULANTE_ANEXO_A_FK FOREIGN KEY (NRO_FOLIO_A) REFERENCES ANEXO_A (NRO_FOLIO_A),
CONSTRAINT POSTULANTE_NACIONALIDAD_FK FOREIGN KEY (ID_NACIONALIDAD) REFERENCES NACIONALIDAD (ID_NACIONALIDAD),
CONSTRAINT POSTULANTE_ESTADO_CIVIL_FK FOREIGN KEY (ID_ESTADO_CIVIL) REFERENCES ESTADO_CIVIL (ID_ESTADO_CIVIL)
);
--REGION
CREATE TABLE REGION
(
ID_REGION NUMBER (3) NOT NULL,
REGION VARCHAR2 (150) NOT NULL,
PORCENTAJE_PUNTAJE NUMERIC (3,2) NULL,
CONSTRAINT REGION_PK PRIMARY KEY (ID_REGION)
);
--COMUNA
CREATE TABLE COMUNA
(ID_COMUNA NUMBER (5) NOT NULL,
COMUNA VARCHAR2 (25) NOT NULL,
ID_REGION NUMBER (3) NOT NULL,
CONSTRAINT COMUNA_PK PRIMARY KEY (ID_COMUNA),
CONSTRAINT COMUNA_REGION_FK FOREIGN KEY (ID_REGION) REFERENCES REGION (ID_REGION)
);
--TITULO POSTULACION
CREATE TABLE TITULO_POSTULACION
(ID_TITULO_POSTULACION VARCHAR2 (20) NOT NULL,
DESCRIPCION VARCHAR2 (30) NOT NULL,
CONSTRAINT TITULO_POSTULACION_PK PRIMARY KEY (ID_TITULO_POSTULACION)
);
--UBICACION PREFERENCIA
CREATE TABLE UBICACION_PREFERENCIA
(NRO_FOLIO_A NUMBER (10) NOT NULL,
VALOR_VIVIENDA NUMBER (10) NOT NULL,
ID_TITULO_POSTULACION VARCHAR2 (20) NOT NULL,
ID_COMUNA NUMBER (5) NOT NULL,
CONSTRAINT UBICACION_PREFERENCIA_PK PRIMARY KEY (NRO_FOLIO_A),
CONSTRAINT UBICACION_ANEXO_A_FK FOREIGN KEY (NRO_FOLIO_A) REFERENCES ANEXO_A (NRO_FOLIO_A),
CONSTRAINT UBICACION_TITULO_FK FOREIGN KEY (ID_TITULO_POSTULACION) REFERENCES TITULO_POSTULACION (ID_TITULO_POSTULACION),
CONSTRAINT UBICACION_COMUNA_FK FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA (ID_COMUNA)
);
--DOMICILIO
CREATE TABLE DOMICILIO
(NRO_FOLIO_A NUMBER (10) NOT NULL,
NUMERO NUMBER (6) NOT NULL,
CALLE VARCHAR2 (25) NOT NULL,
BLOCK NUMBER (3),
DEPTO VARCHAR2 (25),
MANZANA VARCHAR2 (25) NOT NULL,
SITIO VARCHAR2 (25),
POBLACION_VILLA VARCHAR2 (50) NOT NULL,
LOCALIDAD VARCHAR2 (50) NOT NULL,
ID_COMUNA NUMBER (5) NOT NULL,
CONSTRAINT DOMICILIO_PK PRIMARY KEY (NRO_FOLIO_A),
CONSTRAINT DOMICILIO_ANEXO_A_FK FOREIGN KEY (NRO_FOLIO_A) REFERENCES ANEXO_A (NRO_FOLIO_A),
CONSTRAINT DOMILICIO_COMUNA_FK FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA (ID_COMUNA)
);
--ANEXO D
CREATE TABLE ANEXO_D
(NRO_FOLIO_D NUMBER (8) NOT NULL,
CONDICION_MINIMA_VIVIENDA NUMBER(1),
NRO_FOLIO_A NUMBER (10) NOT NULL,
CONSTRAINT ANEXO_D_PK PRIMARY KEY (NRO_FOLIO_D),
CONSTRAINT ANEXO_D_ANEXO_A_FK FOREIGN KEY (NRO_FOLIO_A) REFERENCES ANEXO_A (NRO_FOLIO_A)
);
--PROPIETARIO VIVIENDA
CREATE TABLE PROPIETARIO_VIVIENDA
(NRO_FOLIO_D NUMBER (8) NOT NULL,
RUN_PROPIETARIO NUMBER (10) NOT NULL,
NOMBRE_COMPLETO VARCHAR2 (150) NOT NULL,
TELEFONO NUMBER(10) ,
CORREO VARCHAR2 (50),
CONSTRAINT PROPIETARIO_VIVIENDA_PK PRIMARY KEY (NRO_FOLIO_D),
CONSTRAINT PROPIETARIO_ANEXO_D_FK FOREIGN KEY (NRO_FOLIO_D) REFERENCES ANEXO_D (NRO_FOLIO_D)
);
--DATO RESPONSABLE INFORME
CREATE TABLE DATO_RESPONSABLE_INFORME
(NRO_FOLIO_D NUMBER (8) NOT NULL,
NRO_DATO_DOC NUMBER (10) NOT NULL,
CONSTRAINT DATO_RESPONSABLE_PK PRIMARY KEY (NRO_FOLIO_D, NRO_DATO_DOC),
CONSTRAINT DATO_ANEXO_D_FK FOREIGN KEY (NRO_FOLIO_D) REFERENCES ANEXO_D (NRO_FOLIO_D),
CONSTRAINT DATO_DATO_DOCUMENTO_FK FOREIGN KEY (NRO_DATO_DOC) REFERENCES DATO_DOCUMENTO (NRO_DATO_DOC)
);
--TIPO SUBSIDIO
CREATE TABLE TIPO_SUBSIDIO
(TIPO_TRAMO VARCHAR2 (25) NOT NULL,
DESCRIPCION VARCHAR2 (35) NOT NULL,
CONSTRAINT TIPO_SUBSIDIO_PK PRIMARY KEY (TIPO_TRAMO)
);
--SOLICITUD
CREATE TABLE SOLICITUD
(NRO_FOLIO_D NUMBER(8) NOT NULL,
FECHA_SOLICITUD DATE NOT NULL,
FECHA_EXPIRACION DATE NOT NULL,
TIPO_TRAMO VARCHAR2 (25) NOT NULL,
CONSTRAINT SOLICITUD_PK PRIMARY KEY (NRO_FOLIO_D),
CONSTRAINT SOLICITUD_ANEXO_D_FK FOREIGN KEY (NRO_FOLIO_D) REFERENCES ANEXO_D (NRO_FOLIO_D),
CONSTRAINT SOLICITUD_TIPO_SUBSIDIO_FK FOREIGN KEY (TIPO_TRAMO) REFERENCES TIPO_SUBSIDIO (TIPO_TRAMO)
);
--ANTECEDENTES ADM VIVIENDA
CREATE TABLE ANTECEDENTES_ADM_VIVIENDA
(NRO_FOLIO_D NUMBER (8) NOT NULL,
NRO_PERMISO_EDIFICACION NUMBER (5) NOT NULL,
FECHA_PERMISO DATE NOT NULL,
METROS_CUADRADOS NUMBER (4,2) NOT NULL,
AÑO_CONSTRUCCION_VIV DATE NOT NULL,
NRO_RECEPCION_FINAL NUMBER (5) NOT NULL,
FECHA_RECEPCION DATE NOT NULL,
CONSTRAINT ANTECEDENTES_ADM_PK PRIMARY KEY (NRO_FOLIO_D),
CONSTRAINT ANTECEDENTES_ADM_ANEXO_D_FK FOREIGN KEY (NRO_FOLIO_D) REFERENCES ANEXO_D (NRO_FOLIO_D)
);
--CATEGORIA CONSULTOR
CREATE TABLE CATEGORIA_CONSULTOR
(ID_CATEGORIA_CONSULTOR NUMBER (3) NOT NULL,
CATEGORIA VARCHAR2 (150) NOT NULL,
CONSTRAINT CATEGORIA_CONSULTOR_PK PRIMARY KEY (ID_CATEGORIA_CONSULTOR)
);
--ANTECEDENTES CONSULTOR
CREATE TABLE ANTECEDENTES_CONSULTOR
(RUN_CONSULTOR NUMBER (10) NOT NULL,
NOMBRE_CONSULTOR VARCHAR2 (100) NOT NULL,
TELEFONO NUMBER (20) NOT NULL,
CORREO VARCHAR (100) NOT NULL,
ROL_CONSULTOR VARCHAR2 (30) NOT NULL,
ID_CATEGORIA_CONSULTOR NUMBER (3) NOT NULL,
CONSTRAINT ANTECEDENTES_CONSULTOR_PK PRIMARY KEY (RUN_CONSULTOR),
CONSTRAINT ANTECEDENTES_CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA_CONSULTOR) REFERENCES CATEGORIA_CONSULTOR (ID_CATEGORIA_CONSULTOR)
);
--ANEXO D CONSULTOR
CREATE TABLE ANEXO_D_CONSULTOR
(NRO_FOLIO_D NUMBER (8) NOT NULL,
RUN_CONSULTOR NUMBER (10) NOT NULL,
NRO_RESOLUCION NUMBER (6) NOT NULL,
FECHA_RESOLUCION DATE NOT NULL,
CONSTRAINT ANEXO_D_CONSULTOR_PK PRIMARY KEY (NRO_FOLIO_D, RUN_CONSULTOR),
CONSTRAINT ANEXO_D_FK FOREIGN KEY (NRO_FOLIO_D) REFERENCES ANEXO_D (NRO_FOLIO_D),
CONSTRAINT CONSULTOR_FK FOREIGN KEY (RUN_CONSULTOR) REFERENCES ANTECEDENTES_CONSULTOR (RUN_CONSULTOR)
);
--CARACTERISTICAS VIVIENDA
CREATE TABLE CARACTERISTICA_VIVIENDA
(NRO_FOLIO_D NUMBER (8) NOT NULL,
ROL_SII NUMBER (10) NOT NULL,
USADA NUMBER (1) NOT NULL,
ECONOMICA NUMBER (1) NOT NULL,
DIRECCION VARCHAR2 (50) NOT NULL,
NRO_DEPTO NUMBER (5),
NRO_PISOS NUMBER (3),
NOMBRE_ZONA_VIVIENDA VARCHAR2 (100) NOT NULL,
ID_COMUNA NUMBER (5) NOT NULL,
CONSTRAINT CARACTERISTICAS_PK PRIMARY KEY (NRO_FOLIO_D),
CONSTRAINT CARACTERISTICAS_ANEXO_D_FK FOREIGN KEY (NRO_FOLIO_D) REFERENCES ANEXO_D (NRO_FOLIO_D),
CONSTRAINT CARACTERISTICAS_COMUNA_FK FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA (ID_COMUNA)
);
--TIPO AGRUPACION VIVIENDA
CREATE TABLE TIPO_AGRUP_VIVIENDA
(ID_AGRUPACION_VIVIENDA NUMBER (3) NOT NULL,
NOMBRE_AGRUPACION VARCHAR2 (35) NOT NULL,
CONSTRAINT TIPO_AGRUP_VIVIENDA_PK PRIMARY KEY (ID_AGRUPACION_VIVIENDA)
);
--TIPO VIVIENDA
CREATE TABLE TIPO_VIVIENDA
(ID_TIPO_VIVIENDA NUMBER (2) NOT NULL,
NOMBRE_TIPO_VIVIENDA VARCHAR2 (20) NOT NULL,
CONSTRAINT TIPO_VIVIENDA_PK PRIMARY KEY (ID_TIPO_VIVIENDA)
);
--ESTADO CONSERVACION VIVIENDA
CREATE TABLE ESTADO_CONSER_VIV
(TIPO_ESTADO number (10) NOT NULL,
ESTADO varchar(10) NOT NULL,
CONSTRAINT ESTADO_CONSER_VIV_PK PRIMARY KEY (TIPO_ESTADO)
);
--ANTECEDENTES CONSTRUCCION VIVIENDA
CREATE TABLE ANTECEDENTES_CONSTR_VIV
(NRO_FOLIO_D NUMBER (8) NOT NULL,
NRO_PISOS NUMBER (3) NOT NULL,
SUPERFICIE_VIVIENDA_M2 NUMBER (4,2) NOT NULL,
SUPERFICIE_TERRENO_M2 NUMBER (4,2) NOT NULL,
ID_AGRUPACION_VIVIENDA NUMBER (3) NOT NULL,
ID_TIPO_VIVIENDA NUMBER (2) NOT NULL,
TIPO_ESTADO number (5) NOT NULL,
CONSTRAINT ANTECEDENTES_CONSTR_PK PRIMARY KEY (NRO_FOLIO_D),
CONSTRAINT ANTECEDENTES_AGRUPACION_FK FOREIGN KEY (ID_AGRUPACION_VIVIENDA) REFERENCES TIPO_AGRUP_VIVIENDA (ID_AGRUPACION_VIVIENDA),
CONSTRAINT ANTECEDENTES_TIPO_VIV_FK FOREIGN KEY (ID_TIPO_VIVIENDA) REFERENCES TIPO_VIVIENDA (ID_TIPO_VIVIENDA),
CONSTRAINT ANTECEDENTES_EST_CONSER_FK FOREIGN KEY (TIPO_ESTADO) REFERENCES ESTADO_CONSER_VIV (TIPO_ESTADO)
);
--ESTRUCTURA
CREATE TABLE ESTRUCTURA
(ID_ESTRUCTURA NUMBER (4) NOT NULL,
NOMBRE_ESTRUCTURA VARCHAR2 (35) NOT NULL,
CONSTRAINT ESTRUCTURA_PK PRIMARY KEY (ID_ESTRUCTURA)
);
--MATERIAL
CREATE TABLE MATERIAL
(ID_MATERIAL NUMBER (2) NOT NULL,
NOMBRE_MATERIAL VARCHAR2 (25) NOT NULL,
CONSTRAINT MATERIAL_PK PRIMARY KEY (ID_MATERIAL)
);
--ANTECEDENTES MATERIAL ESTRUCTURA
CREATE TABLE ANT_MATERIAL_ESTRUCTURA
(NRO_FOLIO_D NUMBER (8) NOT NULL,
ID_ESTRUCTURA NUMBER (4) NOT NULL,
ID_MATERIAL NUMBER (2) NOT NULL,
CONSTRAINT ANT_MATERIAL_PK PRIMARY KEY (NRO_FOLIO_D, ID_ESTRUCTURA),
CONSTRAINT ANT_MATERIAL_ANT_CONST_VIV_FK FOREIGN KEY (NRO_FOLIO_D) REFERENCES ANTECEDENTES_CONSTR_VIV (NRO_FOLIO_D),
CONSTRAINT ANT_MATERIAL_ESTRUCTURA_FK FOREIGN KEY (ID_ESTRUCTURA) REFERENCES ESTRUCTURA (ID_ESTRUCTURA),
CONSTRAINT ANT_MATERIAL_MAT_FK FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL (ID_MATERIAL)
);
--TIPO HABITACION
CREATE TABLE TIPO_HABITACION
(ID_TIPO_HAB NUMBER (3) NOT NULL,
NOMBRE_TIPO_HAB VARCHAR2 (35) NOT NULL,
CONSTRAINT TIPO_HABITACION_PK PRIMARY KEY (ID_TIPO_HAB)
);
--ANTECEDENTES TIPO HABITACION
CREATE TABLE ANTECEDENTE_TIPO_HAB
(NRO_FOLIO_D NUMBER (8) NOT NULL,
ID_TIPO_HAB NUMBER (3) NOT NULL,
CANTIDAD NUMBER (2),
CONSTRAINT ANT_TIPO_HAB_PK PRIMARY KEY (NRO_FOLIO_D, ID_TIPO_HAB),
CONSTRAINT ANT_TIPO_ANT_CONST_VIV_FK FOREIGN KEY (NRO_FOLIO_D) REFERENCES ANTECEDENTES_CONSTR_VIV (NRO_FOLIO_D),
CONSTRAINT ANT_TIPO_HAB_FK FOREIGN KEY (ID_TIPO_HAB) REFERENCES TIPO_HABITACION (ID_TIPO_HAB)
);
--DIFICULTAD
CREATE TABLE DIFICULTAD
(ID_DIFICULTAD NUMBER (5) NOT NULL,
DESCRIPCION VARCHAR2 (45) NOT NULL,
CONSTRAINT DIFICULTAD_PK PRIMARY KEY (ID_DIFICULTAD)
);
--ANOMALIA
CREATE TABLE ANOMALIA
(ID_ANOMALIA NUMBER (3) NOT NULL,
DESCRIPCION_ANOMALIA VARCHAR2 (45) NOT NULL,
ID_DIFICULTAD NUMBER (5) NOT NULL,
CONSTRAINT ANOMALIA_PK PRIMARY KEY (ID_ANOMALIA),
CONSTRAINT ANOMALIA_DIFICULTAD_FK FOREIGN KEY (ID_DIFICULTAD) REFERENCES DIFICULTAD (ID_DIFICULTAD)
);
--ANTECEDENTES ANOMALIA
CREATE TABLE ANTECEDENTES_ANOMALIA
(NRO_FOLIO_D NUMBER (8) NOT NULL,
ID_ANOMALIA NUMBER (3) NOT NULL,
EXISTE NUMBER (3) NOT NULL,
CONSTRAINT ANTECEDENTES_ANOMALIAS_PK PRIMARY KEY (NRO_FOLIO_D, ID_ANOMALIA),
CONSTRAINT ANOMALIA_ANT_CONSTR_FK FOREIGN KEY (NRO_FOLIO_D) REFERENCES ANTECEDENTES_CONSTR_VIV (NRO_FOLIO_D),
CONSTRAINT ANT_ANOMALIA_ANOMALIA_FK FOREIGN KEY (ID_ANOMALIA) REFERENCES ANOMALIA (ID_ANOMALIA)
);
--OTRO DAÑO
CREATE TABLE OTRO_DAÑO
(NRO_FOLIO_D NUMBER (8) NOT NULL,
NRO_DAÑO NUMBER (3) NOT NULL,
DESCRIPCION VARCHAR2 (150) NOT NULL,
ID_DIFICULTAD NUMBER (5) NOT NULL,
CONSTRAINT OTRO_DAÑO_PK PRIMARY KEY (NRO_FOLIO_D, NRO_DAÑO),
CONSTRAINT ANT_CONSTR_VIV_DAÑO_FK FOREIGN KEY (NRO_FOLIO_D) REFERENCES ANTECEDENTES_CONSTR_VIV (NRO_FOLIO_D),
CONSTRAINT DAÑO_DIFICULTAD_FK FOREIGN KEY (ID_DIFICULTAD) REFERENCES DIFICULTAD (ID_DIFICULTAD)
);
--POSTULANTE_PUNTAJE
CREATE TABLE POSTULANTE_PUNTAJE
(RUN_POSTULANTE NUMBER (10) NOT NULL,
EDAD NUMBER (3) NOT NULL,
PUNTAJE_EDAD NUMBER (4) NOT NULL,
CARGAS_FAMILIARES NUMBER (2) NOT NULL,
PUNTAJE_CARGAS_FAMILIARES NUMBER (4) NOT NULL,
ESTADO_CIVIL VARCHAR2 (35) NOT NULL,
PUNTAJE_ESTADO_CIVIL NUMBER (4) NOT NULL,
PUEBLO_IND_ORIG VARCHAR2 (35) NOT NULL,
PUNTAJE_PUEBLO_IND_ORIG NUMBER (4) NOT NULL,
MONTO_AHORRO NUMBER (15) NOT NULL,
PUNTAJE_MONTO_AHORRO NUMBER(4) NOT NULL,
TITULO VARCHAR2 (150) NOT NULL,
PUNTAJE_TITULO NUMBER (4) NOT NULL,
PUNTAJE_TOTAL NUMBER (4) NOT NULL,
CONSTRAINT PUNTAJE_PK PRIMARY KEY (RUN_POSTULANTE)
);
--ERROR ASIGNACION PUNTAJE
CREATE TABLE ERRORES_PROC_ASIG_PUNTAJE
(ID_ERROR NUMBER (9) NOT NULL,
NOMBRE_SUBPROGRAMABA VARCHAR2 (100) NOT NULL,
MENSAJE_ERROR VARCHAR2 (500) NOT NULL,
CONSTRAINT ERRORES_PROC_PK PRIMARY KEY (ID_ERROR)
);

CREATE TABLE vivienda_elegida 
(
  nro_folio_A NUMERIC(10) PRIMARY KEY,
  nro_folio_D NUMERIC(8) NOT NULL,
  CONSTRAINT fk_vivienda_elegida_fa FOREIGN KEY (nro_folio_A) REFERENCES anexo_a (nro_folio_A),
  CONSTRAINT fk_vivienda_elegida_fd FOREIGN KEY (nro_folio_D) REFERENCES anexo_d (nro_folio_D)
);

--SECUENCIAS
CREATE SEQUENCE SEQ_idRegion START WITH 10 INCREMENT BY 10;
CREATE SEQUENCE SEQ_idComuna START WITH 10 INCREMENT BY 10;
CREATE SEQUENCE SEQ_ROLCONSULTOR START WITH 100 INCREMENT BY 10;
CREATE SEQUENCE SEQ_NRORESSOLUCION START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_idInstitucion;
CREATE SEQUENCE SEQ_IdColegio;
CREATE SEQUENCE SEQ_ID_ENTAC;
CREATE SEQUENCE SEQ_TIPOCUENTA;
CREATE SEQUENCE SEQ_RELACIONT;
CREATE SEQUENCE SEQ_NROFOLIO_A START WITH 1000000000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NROFOLIO_D START WITH 20000000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IDCAT;
CREATE SEQUENCE SEQ_ID_TIPOVIVAGRUP;
CREATE SEQUENCE SEQ_IDTIPOVIV;
CREATE SEQUENCE SEQ_IDESTRUC;
CREATE SEQUENCE SEQ_IDMATER;
CREATE SEQUENCE SEQ_IDTIPOHAB;
CREATE SEQUENCE SEQ_DIFICULTAD;
CREATE SEQUENCE SEQ_ANOMALIAS;
CREATE SEQUENCE SEQ_OTRODAÑO;
CREATE SEQUENCE SEQ_ERRORES_PROC_ASIG_PUNTAJE;


/

COMMIT;