SELECT P.RUN_POSTULANTE, 
TO_CHAR(A.FECHA_RECEPCION,'DD/MM/YYYY'),
A.NOMBRE_RECEPTOR,
P.NOMBRES||' '|| P.PRIMER_APELLIDO||' '||P.SEGUNDO_APELLIDO AS NOMBRES,
P.FECHA_NACIMIENTO,
N.NACIONALIDAD,
E.ESTADO_CIVIL,
pkg_postulante.fn_total_cargas_familiares(P.RUN_POSTULANTE) AS TOTAL_CARGAS,
NVL(Z.PERTENECE_PUEBLO_IND_ORIG,0) AS PERTENECE_PUEBLO,
NVL(T.TITULO,'NO POSEE') AS TITULO,
NVL(C.RUN_CONVIVIENTE,0) AS RUN_CONYUGE,
nvl(C.NOMBRES||' '||C.PRIMER_APELLIDO||' '||C.SEGUNDO_APELLIDO, 'no posee') AS NOMBRE_CONYUGE,
D.CALLE,
D.NUMERO,
NVL(D.BLOCK,0) AS BLOCK,
NVL(D.DEPTO,'NO POSEE')AS DEPTO,
D.MANZANA,
NVL(D.SITIO,'NO POSEE') AS SITIO,
X.COMUNA,
R.REGION,
NVL(Y.FONO_TRABAJO,0) AS FONO_TRABAJO,
NVL(Y.FONO_DOMICILIO,0) AS FONO_DOMICILIO,
Y.FONO_MOVIL,
NVL(Y.CODIGO_POSTAL,0) AS CODIGO_POSTAL,
Y.EMAIL,
U.ID_TITULO_POSTULACION,
CO.COMUNA AS COMUNA_SUBSIDIO,
RE.REGION AS REGION_SUBSIDIO,
TI.NOMBRE_TIPO_VIVIENDA TIPO_VIVIENDA,
to_char(U.VALOR_VIVIENDA,'$9g999g999g999') as VALOR_VIVIENDA,
to_char(MO.MONTO_AHORRADO,'$9g999g999g999') AS MONTO_AHORRADO,
    NVL((SELECT AVG(PUNTAJE_TOTAL) FROM POSTULANTE_PUNTAJE),0) AS PUNTAJE_MINIMO,
    NVL(PU.PUNTAJE_TOTAL,0)
FROM POSTULANTE P JOIN ANEXO_A A
ON (P.NRO_FOLIO_A = A.NRO_FOLIO_A)
JOIN NACIONALIDAD N
ON (P.ID_NACIONALIDAD = N.ID_NACIONALIDAD)
JOIN ESTADO_CIVIL E
ON (P.ID_ESTADO_CIVIL = E.ID_ESTADO_CIVIL)
JOIN ACREDITACIONES Z
ON(Z.NRO_FOLIO_A = P.NRO_FOLIO_A)
LEFT JOIN TITULO T
ON (T.NRO_FOLIO_A = Z.NRO_FOLIO_A)
LEFT JOIN CONVIVIENTE_CIVIL C
ON (C.NRO_FOLIO_A = P.NRO_FOLIO_A)
LEFT JOIN DOMICILIO D
ON (D.NRO_FOLIO_A = P.NRO_FOLIO_A)
JOIN COMUNA X
ON(X.ID_COMUNA = D.ID_COMUNA)
JOIN REGION R 
ON(R.ID_REGION = X.ID_REGION)
LEFT JOIN CONTACTO Y
ON(Y.NRO_FOLIO_A = P.NRO_FOLIO_A)
JOIN UBICACION_PREFERENCIA U
ON (U.NRO_FOLIO_A = P.NRO_FOLIO_A)
JOIN COMUNA CO
ON(U.ID_COMUNA = CO.ID_COMUNA)
JOIN REGION RE
ON(CO.ID_REGION = RE.ID_REGION)
JOIN ANEXO_D DE
ON(DE.NRO_FOLIO_A = A.NRO_FOLIO_A)
JOIN antecedentes_constr_viv ACV
ON(ACV.NRO_FOLIO_D = DE.NRO_FOLIO_D)
LEFT JOIN TIPO_VIVIENDA TI
ON(ACV.ID_TIPO_VIVIENDA = TI.ID_TIPO_VIVIENDA)
JOIN AHORRO MO
ON(MO.NRO_FOLIO_A = P.NRO_FOLIO_A)
LEFT JOIN POSTULANTE_PUNTAJE PU
ON(P.RUN_POSTULANTE = PU.RUN_POSTULANTE);




select * from postulante_puntaje;
