--Necesita SYS

--Crear Usuario Dueño

CREATE USER SUBSIDIO IDENTIFIED BY "123";
GRANT DBA, CONNECT, RESOURCE TO SUBSIDIO;
GRANT READ, WRITE ON DIRECTORY ORACLECLRDIR TO SUBSIDIO;
GRANT CREATE SESSION TO SUBSIDIO;




--Crear Roles
--rol consulta
CREATE ROLE ROL_CONSULTA;
GRANT RESOURCE, CONNECT TO ROL_CONSULTA;
GRANT SELECT ON SUBSIDIO.view_postulante_beneficiado TO ROL_CONSULTA; 
/
DECLARE
  v_rol_name VARCHAR2(100) := 'ROL_CONSULTA';
  v_owner VARCHAR2(100) := 'SUBSIDIO';
BEGIN
  FOR reg_table IN (SELECT table_name FROM all_tables WHERE owner = v_owner) LOOP
    EXECUTE IMMEDIATE 
      'GRANT SELECT ON ' || v_owner || '.' || reg_table.table_name || ' TO ' || v_rol_name;
      DBMS_OUTPUT.PUT_LINE('table grant select: ' || v_owner || ' - ' || reg_table.table_name);
    EXECUTE IMMEDIATE  
      'CREATE OR REPLACE PUBLIC SYNONYM ' || reg_table.table_name || ' FOR SUBSIDIO.' || reg_table.table_name;  
  END LOOP;
  EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('FALLO DE LA ASIGNACION PRIVILEGIOS O SYNONYM EN ROL_CONSULTA');
END;
/
GRANT EXECUTE ON SUBSIDIO.PKG_POSTULANTE TO ROL_CONSULTA;
GRANT EXECUTE ON SUBSIDIO.fn_obtener_puntaje_cargas_fam TO ROL_CONSULTA;
GRANT EXECUTE ON SUBSIDIO.fn_obtener_puntaje_ahorro TO ROL_CONSULTA;
GRANT EXECUTE ON SUBSIDIO.fn_obtener_id_region TO ROL_CONSULTA;
GRANT EXECUTE ON SUBSIDIO.fn_obtener_region_porcentaje TO ROL_CONSULTA;
GRANT EXECUTE ON SUBSIDIO.fn_obtener_region_nombre TO ROL_CONSULTA;
GRANT EXECUTE ON SUBSIDIO.fn_calcular_edad TO ROL_CONSULTA;
GRANT EXECUTE ON SUBSIDIO.fn_puntaje_edad TO ROL_CONSULTA;
GRANT EXECUTE ON SUBSIDIO.SP_ASIGNAR_PUNTAJES TO ROL_CONSULTA;






--rol administra
CREATE ROLE ROL_ADMINISTRA;
GRANT RESOURCE, CONNECT TO ROL_ADMINISTRA;
GRANT SELECT ON SUBSIDIO.view_postulante_beneficiado TO ROL_ADMINISTRA;
/
DECLARE
  v_rol_name VARCHAR2(100) := 'ROL_ADMINISTRA';
  v_owner VARCHAR2(100) := 'SUBSIDIO';
BEGIN
  FOR reg_table IN (SELECT table_name FROM all_tables WHERE owner = v_owner) LOOP
    EXECUTE IMMEDIATE 
      'GRANT SELECT, UPDATE ON ' || v_owner || '.' || reg_table.table_name || ' TO ' || v_rol_name;
      DBMS_OUTPUT.PUT_LINE('table grant select, update: ' || v_owner || ' - ' || reg_table.table_name);
    EXECUTE IMMEDIATE  
      'CREATE OR REPLACE PUBLIC SYNONYM ' || reg_table.table_name || ' FOR SUBSIDIO.' || reg_table.table_name;
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('FALLO DE LA ASIGNACION PRIVILEGIOS O SYNONYM EN ROL_ADMINISTRA');
END;
/
GRANT EXECUTE ON SUBSIDIO.PKG_POSTULANTE TO ROL_ADMINISTRA;
GRANT EXECUTE ON SUBSIDIO.fn_obtener_puntaje_cargas_fam TO ROL_ADMINISTRA;
GRANT EXECUTE ON SUBSIDIO.fn_obtener_puntaje_ahorro TO ROL_ADMINISTRA;
GRANT EXECUTE ON SUBSIDIO.fn_obtener_id_region TO ROL_ADMINISTRA;
GRANT EXECUTE ON SUBSIDIO.fn_obtener_region_porcentaje TO ROL_ADMINISTRA;
GRANT EXECUTE ON SUBSIDIO.fn_obtener_region_nombre TO ROL_ADMINISTRA;
GRANT EXECUTE ON SUBSIDIO.fn_calcular_edad TO ROL_ADMINISTRA;
GRANT EXECUTE ON SUBSIDIO.fn_puntaje_edad TO ROL_ADMINISTRA;
GRANT EXECUTE ON SUBSIDIO.SP_ASIGNAR_PUNTAJES TO ROL_ADMINISTRA;



--Asignar roles
CREATE USER ADMINISTRADOR IDENTIFIED BY "123";
CREATE USER CONSULTOR IDENTIFIED BY "123";

GRANT ROL_ADMINISTRA TO ADMINISTRADOR;
GRANT ROL_CONSULTA TO CONSULTOR;

COMMIT;